name: CI/CD workflow
on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: run superlinter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Test project
        run: npm test

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/walking-skeleton-js:latest,${{ secrets.DOCKERHUB_USERNAME }}/walking-skeleton-js:${{github.run_number}}
  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
    - name: SSH to instance
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secret. INSTANCE_USER }}
        key: ${{ secret. INSTANCE_KEY }}
    
    - name: Deploy app
      run: |
      docker pull mherreral/walking-skeleton-js
      docker run -p 8080:3000 mherreral/walking-skeleton-js