name: CI/CD workflow
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm test

  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build --if-present

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/walking-skeleton-js:latest,${{ secrets.DOCKERHUB_USERNAME }}/walking-skeleton-js:${{github.run_number}}
  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: sanhidalgoo,mherreral,juansedo
          minimum-approvals: 1
      - name: Install and run docker
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets. INSTANCE_USER }}
          key: ${{ secrets. INSTANCE_KEY }}
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull mherreral/walking-skeleton-js
            docker run -p 80:3000 -d mherreral/walking-skeleton-js:latest
